/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaassignment2;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ruchitesh
 */
public class BankForm extends javax.swing.JFrame {

    /**
     * Creates new form BankForm
     */
    Statement statement ;
    Connection con;
    public BankForm() {
        initComponents();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/","root","");
            statement=con.createStatement();
            statement.executeUpdate("CREATE DATABASE IF NOT EXISTS Bank_db");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Bank_db","root","");
            statement =con.createStatement();
            statement.executeUpdate("CREATE TABLE IF NOT EXISTS Account  (`Accno` INT PRIMARY KEY,`Name` VARCHAR(30),`Balance` INT,Phone VARCHAR(10),`Address` VARCHAR(50))");
        } catch (Exception ex) {
            Logger.getLogger(BankForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbaccno = new javax.swing.JTextField();
        accno = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        tbname = new javax.swing.JTextField();
        balance = new javax.swing.JLabel();
        tbbalance = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        tbphone = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        tbaddress = new javax.swing.JTextField();
        insertbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        status = new javax.swing.JLabel();
        displaybtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbaccno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbaccnoActionPerformed(evt);
            }
        });

        accno.setText("Account No");

        name.setText("Name          ");

        tbname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnameActionPerformed(evt);
            }
        });

        balance.setText("Balance");

        tbbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbbalanceActionPerformed(evt);
            }
        });

        phone.setText(" Phone        ");

        tbphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbphoneActionPerformed(evt);
            }
        });

        address.setText("Address      ");

        tbaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbaddressActionPerformed(evt);
            }
        });

        insertbtn.setText("Insert");
        insertbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No", "Name", "Balance", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        status.setText("Status : ");

        displaybtn.setText("Display");
        displaybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displaybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(accno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tbaddress, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(tbphone)
                                    .addComponent(tbbalance)
                                    .addComponent(tbname)
                                    .addComponent(tbaccno))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(150, 150, 150))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displaybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbaccno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balance))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insertbtn)
                        .addGap(18, 18, 18)
                        .addComponent(updatebtn)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(phone)
                            .addComponent(tbphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tbaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deletebtn)
                        .addGap(22, 22, 22)
                        .addComponent(displaybtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbaccnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbaccnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbaccnoActionPerformed

    private void tbnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnameActionPerformed

    private void tbbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbbalanceActionPerformed

    private void tbphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbphoneActionPerformed

    private void tbaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbaddressActionPerformed

    private void insertbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbtnActionPerformed
        try {
            // TODO add your handling code here:
            int res=statement.executeUpdate("insert into account VALUES("
                    + "'"+tbaccno.getText()+"',"
                    +"'"+tbname.getText()+"',"
                    +tbbalance.getText()
                    +",'"+tbphone.getText()+"',"
                    +"'"+tbaddress.getText()+"')"
            );
            if(res>0)
                status.setText("Success!");
            else
                status.setText("Failed!");
        } catch (SQLException ex) {
            Logger.getLogger(BankForm.class.getName()).log(Level.SEVERE, null, ex);
            status.setText("Failed!");
        }
    }//GEN-LAST:event_insertbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       try {
            // TODO add your handling code here:
            PreparedStatement updt=con.prepareStatement("UPDATE `account` SET `Name`=?,`Balance`=?,`Phone`=?,`Address`=? where Accno=?");
            updt.setString(1,tbname.getText());
            updt.setInt(2,Integer.parseInt(tbbalance.getText()));
            updt.setString(3,tbphone.getText());
            updt.setString(4,tbaddress.getText());
            updt.setInt(5,Integer.parseInt(tbaccno.getText()));
            int res=updt.executeUpdate();
            if(res>0)
            status.setText("Success!");
            else
                status.setText("Failed!");
        } catch (SQLException ex) {
            Logger.getLogger(BankForm.class.getName()).log(Level.SEVERE, null, ex);
            status.setText("Failed!");
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       PreparedStatement del;
        try {
            del = con.prepareStatement("DELETE from account where Accno=?");
            del.setInt(1,Integer.parseInt(tbaccno.getText()));
             int res=del.executeUpdate();
             if(res>0)
            status.setText("success!");
             else{
                 status.setText("Failed!");
             }
        } catch (SQLException ex) {
            Logger.getLogger(BankForm.class.getName()).log(Level.SEVERE, null, ex);
            status.setText("Failed!");
        }
           
    }//GEN-LAST:event_deletebtnActionPerformed

    private void displaybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displaybtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl.getModel();
       model.setRowCount(0);
        PreparedStatement sel;
        try {
            sel = con.prepareStatement("select * from account where Balance>=20000");
            ResultSet rs = sel.executeQuery();
            while(rs.next()){
               Vector<Object> v = new Vector<>();
               v.add(rs.getInt(1));
               v.add(rs.getString(2));
               v.add(rs.getInt(3));
               v.add(rs.getString(4));
               v.add(rs.getString(5));
               model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(BankForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displaybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accno;
    private javax.swing.JLabel address;
    private javax.swing.JLabel balance;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton displaybtn;
    private javax.swing.JButton insertbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel status;
    private javax.swing.JTextField tbaccno;
    private javax.swing.JTextField tbaddress;
    private javax.swing.JTextField tbbalance;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField tbname;
    private javax.swing.JTextField tbphone;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
